---
rackup: /opt/applications/monk_push/current/config.ru
pid: /tmp/pids/thin_task.pid
wait: 30
timeout: 30
log: /var/log/thin_task
max_conns: 1024
require: []

max_persistent_conns: 512
environment: production
servers: 4
daemonize: true
chdir: /opt/applications/monk_push/current
socket: /tmp/thin_task.sock
